version: '3.7'

services:
  mpd:
    build:
      context: .
      dockerfile: Dockerfile.mpd
    depends_on:
      - snapserver
    volumes:
      - ./music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./mpd-db:/var/lib/mpd
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "6600:6600"

  restore:
    build:
      context: .
      dockerfile: Dockerfile.restore
    volumes:
      - ${SSH_PATH}:/root/.ssh:ro
    ports:
      - "3001:3000"
    restart: unless-stopped

  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "1704:1704"   # Puerto TCP para Snapclient
      - "1705:1705"   # Puerto HTTP para la interfaz web de Snapserver (opcional)
      - "1780:1780"   # Puerto TCP para control remoto (opcional)

  snapclient:
    build:
      context: .
      dockerfile: Dockerfile.snapclient
    command: snapclient ${SNAPCLIENT_OPTS}
    depends_on:
      - snapserver
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd

  dnsmasq:
    image: sirscythe/dnsmasq-arm
    container_name: dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/udp"
      - "5380:8080"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      - HTTP_USER=miguel
      - HTTP_PASS=123
    restart: always
    logging:
      options:
        max-size: "100m"

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: app:latest
    environment:
      - SSH_HOST=${SSH_HOST}
      - SSH_USER=${SSH_USER}
      - SCRIPT_UPDATE_APP_PATH=${SCRIPT_UPDATE_APP_PATH}
    volumes:
      - /home/miguel/.ssh:/home/node/.ssh:ro
    restart: unless-stopped
    ports:
      - "3000:3000"

  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - TZ=Europe/Madrid
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./music:/music
      - ./smb.conf:/etc/samba/smb.conf
    restart: unless-stopped

volumes:
  shared-fifo:
  caddy_data:
  caddy_config:
