version: '3.7'

services:
  snapclient:
    build:
      context: .
      dockerfile: Dockerfile.snapclient
    command: snapclient -h snapserver.casa --latency=${LATENCY}
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
