version: '3.7'

services:
  mpd:
    build:
      context: .
      dockerfile: Dockerfile.mpd
    depends_on:
      - snapserver
    volumes:
      - ./music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./mpd-db:/var/lib/mpd
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "6600:6600"

  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "1704:1704"   # Puerto TCP para Snapclient
      - "1705:1705"   # Puerto HTTP para la interfaz web de Snapserver (opcional)
      - "1780:1780"   # Puerto TCP para control remoto (opcional)

  snapclient:
    build:
      context: .
      dockerfile: Dockerfile.snapclient
    command: snapclient -h snapserver --latency=${LATENCY}
    depends_on:
      - snapserver
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd

  #filebrowser:
  #  image: hurlenko/filebrowser
  #  user: "1000:1001"
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - ./music:/data
  #    - ./config:/config
  #  environment:
  #    - FB_BASEURL=/filebrowser
  #  restart: always
  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - TZ=Europe/Madrid
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./music:/music
      - ./smb.conf:/etc/samba/smb.conf
    restart: unless-stopped

volumes:
  shared-fifo:
