version: '3.7'

services:
  mpd:
    build:
      context: .
      dockerfile: Dockerfile.mpd
    depends_on:
      - snapserver
    volumes:
      - ./music:/var/lib/mpd/music
      - ./playlists:/var/lib/mpd/playlists
      - ./mpd-db:/var/lib/mpd
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "6600:6600"

  snapserver:
    build:
      context: .
      dockerfile: Dockerfile.snapserver
    volumes:
      - ./snapserver.conf:/etc/snapserver.conf
      - shared-fifo:/shared

    restart: unless-stopped
    ports:
      - "1704:1704"   # Puerto TCP para Snapclient
      - "1705:1705"   # Puerto HTTP para la interfaz web de Snapserver (opcional)
      - "1780:1780"   # Puerto TCP para control remoto (opcional)

  snapclient:
    build:
      context: .
      dockerfile: Dockerfile.snapclient
    command: snapclient ${SNAPCLIENT_OPTS}
    depends_on:
      - snapserver
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
  app:
    build:
      context: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - TZ=Europe/Madrid
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./music:/music
      - ./smb.conf:/etc/samba/smb.conf
    restart: unless-stopped
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null
    ports:
      - "5173:5173"
    depends_on:
      - mpd

volumes:
  shared-fifo:
  caddy_data:
  caddy_config:
